fn main() {

    //
    // Part 1
    //
    let mut input: [isize; 14] = [9,9,9,9,9,9,9,9,9,9,9,9,9,9];

    loop {

        // prepare context
        let mut j = 0;
        let mut w = 0;
        let mut x = 0;
        let mut y = 0;
        let mut z = 0;
    
        // Execute program
        w = input[j];
        j += 1;
        x = x * 0;
        x = x + z;
        x = x % 26;
        z = z / 1;
        x = x + 11;
        x = if x == w { 1 } else { 0 };
        x = if x == 0 { 1 } else { 0 };
        y = y * 0;
        y = y + 25;
        y = y * x;
        y = y + 1;
        z = z * y;
        y = y * 0;
        y = y + w;
        y = y + 5;
        y = y * x;
        z = z + y;
        w = input[j];
        j += 1;
        x = x * 0;
        x = x + z;
        x = x % 26;
        z = z / 1;
        x = x + 13;
        x = if x == w { 1 } else { 0 };
        x = if x == 0 { 1 } else { 0 };
        y = y * 0;
        y = y + 25;
        y = y * x;
        y = y + 1;
        z = z * y;
        y = y * 0;
        y = y + w;
        y = y + 5;
        y = y * x;
        z = z + y;
        w = input[j];
        j += 1;
        x = x * 0;
        x = x + z;
        x = x % 26;
        z = z / 1;
        x = x + 12;
        x = if x == w { 1 } else { 0 };
        x = if x == 0 { 1 } else { 0 };
        y = y * 0;
        y = y + 25;
        y = y * x;
        y = y + 1;
        z = z * y;
        y = y * 0;
        y = y + w;
        y = y + 1;
        y = y * x;
        z = z + y;
        w = input[j];
        j += 1;
        x = x * 0;
        x = x + z;
        x = x % 26;
        z = z / 1;
        x = x + 15;
        x = if x == w { 1 } else { 0 };
        x = if x == 0 { 1 } else { 0 };
        y = y * 0;
        y = y + 25;
        y = y * x;
        y = y + 1;
        z = z * y;
        y = y * 0;
        y = y + w;
        y = y + 15;
        y = y * x;
        z = z + y;
        w = input[j];
        j += 1;
        x = x * 0;
        x = x + z;
        x = x % 26;
        z = z / 1;
        x = x + 10;
        x = if x == w { 1 } else { 0 };
        x = if x == 0 { 1 } else { 0 };
        y = y * 0;
        y = y + 25;
        y = y * x;
        y = y + 1;
        z = z * y;
        y = y * 0;
        y = y + w;
        y = y + 2;
        y = y * x;
        z = z + y;
        w = input[j];
        j += 1;
        x = x * 0;
        x = x + z;
        x = x % 26;
        z = z / 26;
        x = x + -1;
        x = if x == w { 1 } else { 0 };
        x = if x == 0 { 1 } else { 0 };
        y = y * 0;
        y = y + 25;
        y = y * x;
        y = y + 1;
        z = z * y;
        y = y * 0;
        y = y + w;
        y = y + 2;
        y = y * x;
        z = z + y;
        w = input[j];
        j += 1;
        x = x * 0;
        x = x + z;
        x = x % 26;
        z = z / 1;
        x = x + 14;
        x = if x == w { 1 } else { 0 };
        x = if x == 0 { 1 } else { 0 };
        y = y * 0;
        y = y + 25;
        y = y * x;
        y = y + 1;
        z = z * y;
        y = y * 0;
        y = y + w;
        y = y + 5;
        y = y * x;
        z = z + y;
        w = input[j];
        j += 1;
        x = x * 0;
        x = x + z;
        x = x % 26;
        z = z / 26;
        x = x + -8;
        x = if x == w { 1 } else { 0 };
        x = if x == 0 { 1 } else { 0 };
        y = y * 0;
        y = y + 25;
        y = y * x;
        y = y + 1;
        z = z * y;
        y = y * 0;
        y = y + w;
        y = y + 8;
        y = y * x;
        z = z + y;
        w = input[j];
        j += 1;
        x = x * 0;
        x = x + z;
        x = x % 26;
        z = z / 26;
        x = x + -7;
        x = if x == w { 1 } else { 0 };
        x = if x == 0 { 1 } else { 0 };
        y = y * 0;
        y = y + 25;
        y = y * x;
        y = y + 1;
        z = z * y;
        y = y * 0;
        y = y + w;
        y = y + 14;
        y = y * x;
        z = z + y;
        w = input[j];
        j += 1;
        x = x * 0;
        x = x + z;
        x = x % 26;
        z = z / 26;
        x = x + -8;
        x = if x == w { 1 } else { 0 };
        x = if x == 0 { 1 } else { 0 };
        y = y * 0;
        y = y + 25;
        y = y * x;
        y = y + 1;
        z = z * y;
        y = y * 0;
        y = y + w;
        y = y + 12;
        y = y * x;
        z = z + y;
        w = input[j];
        j += 1;
        x = x * 0;
        x = x + z;
        x = x % 26;
        z = z / 1;
        x = x + 11;
        x = if x == w { 1 } else { 0 };
        x = if x == 0 { 1 } else { 0 };
        y = y * 0;
        y = y + 25;
        y = y * x;
        y = y + 1;
        z = z * y;
        y = y * 0;
        y = y + w;
        y = y + 7;
        y = y * x;
        z = z + y;
        w = input[j];
        j += 1;
        x = x * 0;
        x = x + z;
        x = x % 26;
        z = z / 26;
        x = x + -2;
        x = if x == w { 1 } else { 0 };
        x = if x == 0 { 1 } else { 0 };
        y = y * 0;
        y = y + 25;
        y = y * x;
        y = y + 1;
        z = z * y;
        y = y * 0;
        y = y + w;
        y = y + 14;
        y = y * x;
        z = z + y;
        w = input[j];
        j += 1;
        x = x * 0;
        x = x + z;
        x = x % 26;
        z = z / 26;
        x = x + -2;
        x = if x == w { 1 } else { 0 };
        x = if x == 0 { 1 } else { 0 };
        y = y * 0;
        y = y + 25;
        y = y * x;
        y = y + 1;
        z = z * y;
        y = y * 0;
        y = y + w;
        y = y + 13;
        y = y * x;
        z = z + y;
        w = input[j];
        j += 1;
        x = x * 0;
        x = x + z;
        x = x % 26;
        z = z / 26;
        x = x + -13;
        x = if x == w { 1 } else { 0 };
        x = if x == 0 { 1 } else { 0 };
        y = y * 0;
        y = y + 25;
        y = y * x;
        y = y + 1;
        z = z * y;
        y = y * 0;
        y = y + w;
        y = y + 6;
        y = y * x;
        z = z + y;

        
        // Check outcome
        if z == 0 {
            println!("{:?} => {}", input, z);
            break;
        }

        // Decrement input
        let mut i = 13;
        while i != 0 {
            if input[i] == 1 {
                input[i] = 9;
                if i != 0 {
                    i -= 1;
                } else {
                    break;
                }
            } else {
                input[i] -= 1;
                break;
            }
        }
    }
}
