[package]
name = "day24"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day24"
path = "./src/main.rs"

[[bin]]
name = "prog"
path = "./src/prog.rs"

[dependencies]
